<a href="https://colab.research.google.com/github/AlexanderYevdokymenko/Machine-learning/blob/main/%D0%84%D0%B2%D0%B4%D0%BE%D0%BA%D0%B8%D0%BC%D0%B5%D0%BD%D0%BA%D0%BE_%D0%9F%D0%A0%E2%84%964_%D0%92%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82%E2%84%9610.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Завдання 1
from sklearn.datasets import load_breast_cancer
import numpy as np
import pandas as pd



In [ ]:
# Завдання 1) Завантажуємо вбудований датасет load_breast_cancer з бібліотеки sklearn.datasets
data = load_breast_cancer()

# Перетворимо дані в DataFrame для зручності
df = pd.DataFrame(data.data, columns=data.feature_names)

# Додаємо цільову змінну до DataFrame
df['target'] = data.target

#1.1 Переглянемо перші кілька рядків
print("Перші рядки датасету:")
print(df.head())

#1.2 Перевіряємо назви стовпців та типи даних
print("\nНазви стовпців та типи даних:")
print(df.dtypes)

#1.3 Перевіряємо наявність пропущених значень
print("\nЧи є пропущені значення?")
print(df.isnull().sum())

#1.4 Розмір даних
print("\nРозмір даних:")
print(df.shape)

Перші рядки датасету:
   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst 

In [ ]:
#2) Побудова і налаштування моделей:

from sklearn.model_selection import train_test_split

#2.1 Розділяємо дані на ознаки (X) і цільову змінну (y)
X = df.drop('target', axis=1)
y = df['target']

#2.2 Розділення на навчальний і тестовий набори (80% для навчання, 20% для тестування)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Створюємо пайплайн для масштабування даних та моделювання
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('logreg', LogisticRegression(max_iter=1000))
])

# Визначаємо сітку параметрів для GridSearchCV
param_grid_lr = {
    'logreg__C': [0.1, 1, 10, 100],
    'logreg__solver': ['lbfgs', 'liblinear']
}

# Налаштовуємо GridSearchCV з пайплайном
grid_lr = GridSearchCV(pipeline, param_grid_lr, cv=5)
grid_lr.fit(X_train, y_train)

print("Найкращі параметри для логістичної регресії:", grid_lr.best_params_)

Найкращі параметри для логістичної регресії: {'logreg__C': 0.1, 'logreg__solver': 'liblinear'}


In [ ]:
from sklearn.tree import DecisionTreeClassifier

# Створюємо модель дерева рішень
tree_clf = DecisionTreeClassifier()

# Підбір параметрів для дерева рішень
param_grid_tree = {'max_depth': [3, 5, 7, 10], 'min_samples_split': [2, 5, 10]}
grid_tree_clf = GridSearchCV(tree_clf, param_grid_tree, cv=5)
grid_tree_clf.fit(X_train, y_train)

# Найкращі параметри
print("\nНайкращі параметри для дерева рішень:", grid_tree_clf.best_params_)



Найкращі параметри для дерева рішень: {'max_depth': 5, 'min_samples_split': 10}


In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Створюємо модель випадкового лісу
rf_clf = RandomForestClassifier()

# Підбір параметрів для випадкового лісу
param_grid_rf = {'n_estimators': [50, 100, 200], 'max_depth': [3, 5, 7, 10]}
grid_rf_clf = GridSearchCV(rf_clf, param_grid_rf, cv=5)
grid_rf_clf.fit(X_train, y_train)

# Найкращі параметри
print("\nНайкращі параметри для випадкового лісу:", grid_rf_clf.best_params_)



Найкращі параметри для випадкового лісу: {'max_depth': 7, 'n_estimators': 50}


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#1 Логістична регресія
log_reg_best = grid_log_reg.best_estimator_
y_pred_log_reg = log_reg_best.predict(X_test)
print("\nТочність логістичної регресії:", accuracy_score(y_test, y_pred_log_reg))
print(confusion_matrix(y_test, y_pred_log_reg))
print(classification_report(y_test, y_pred_log_reg))

#2 Дерево рішень
tree_best = grid_tree_clf.best_estimator_
y_pred_tree = tree_best.predict(X_test)
print("\nТочність дерева рішень:", accuracy_score(y_test, y_pred_tree))
print(confusion_matrix(y_test, y_pred_tree))
print(classification_report(y_test, y_pred_tree))

#3 Випадковий ліс
rf_best = grid_rf_clf.best_estimator_
y_pred_rf = rf_best.predict(X_test)
print("\nТочність випадкового лісу:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))



Точність логістичної регресії: 0.956140350877193
[[39  4]
 [ 1 70]]
              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114


Точність дерева рішень: 0.9298245614035088
[[39  4]
 [ 4 67]]
              precision    recall  f1-score   support

           0       0.91      0.91      0.91        43
           1       0.94      0.94      0.94        71

    accuracy                           0.93       114
   macro avg       0.93      0.93      0.93       114
weighted avg       0.93      0.93      0.93       114


Точність випадкового лісу: 0.9649122807017544
[[40  3]
 [ 1 70]]
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        43
           1       0.96      0.99      

In [ ]:
#3) Вибираємо найкращу модель за точністю
best_model = None
if accuracy_score(y_test, y_pred_log_reg) > max(accuracy_score(y_test, y_pred_tree), accuracy_score(y_test, y_pred_rf)):
    best_model = "Логістична регресія"
elif accuracy_score(y_test, y_pred_tree) > accuracy_score(y_test, y_pred_rf):
    best_model = "Дерево рішень"
else:
    best_model = "Випадковий ліс"

print(f"\nНайкраща модель: {best_model}")



Найкраща модель: Випадковий ліс


In [ ]:
#4) Робимо прогноз на основі найкращої моделі
if best_model == "Логістична регресія":
    y_pred_best = y_pred_log_reg
elif best_model == "Дерево рішень":
    y_pred_best = y_pred_tree
else:
    y_pred_best = y_pred_rf

print("\nПрогноз на тестовій вибірці:")
print(y_pred_best)



Прогноз на тестовій вибірці:
[1 0 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 1 0]


In [ ]:
#2 Завдання

import pandas as pd



data = pd.read_csv('titanic.csv')
