<a href="https://colab.research.google.com/github/AlexanderYevdokymenko/Machine-learning/blob/main/%D0%84%D0%B2%D0%B4%D0%BE%D0%BA%D0%B8%D0%BC%D0%B5%D0%BD%D0%BA%D0%BE_%D0%9F%D0%A0%E2%84%961_%D0%92%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82%E2%84%9610.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Варіант №10

import numpy as np
numpy_version = np.__version__
print(f"NumPy version: {numpy_version}")


NumPy version: 1.26.4


In [ ]:
#Завдання 1
# Створіть одновимірний масив (Вектор) з перших 10 піднесених  до квадрату натуральних чисел та виведіть його значення

vector = np.array([i**2 for i in range(1, 11)])
vector


array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
#Завдання 2
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями квадратних коренів від кожного натурального числа, починаючи з 1, та виведіть його значення.


natural_numbers = np.arange(1, 10)
square_roots = np.sqrt(natural_numbers)
matrix = square_roots.reshape(3, 3)
print(matrix)


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [ ]:
# Завдання 3
#Створіть масив розміром 3x3, заповніть його випадковими цілими числами в діапазоні від 0 до 5 та виведіть його значення.


random_matrix = np.random.randint(0, 6, size=(3, 3))
print(random_matrix)


[[5 1 1]
 [2 5 3]
 [4 1 0]]


In [ ]:
#Завдання 4
#Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть суму елементів, які менше середнього значення.

mean_value = np.mean(matrix)
sum_below_mean = np.sum(matrix[matrix < mean_value])
print("Масив:\n", matrix)
print("Середнє значення:", mean_value)
print("Сума елементів, менших за середнє значення:", sum_below_mean)


Масив:
 [[0.39899979 0.45925672 0.57519486 0.30285185 0.38983148]
 [0.8606784  0.86707535 0.09770646 0.38074288 0.36205839]
 [0.64127202 0.03419375 0.02964057 0.05735376 0.16812693]
 [0.61776567 0.3506411  0.64313313 0.49336266 0.41911959]
 [0.93210886 0.53975191 0.40033474 0.9110835  0.2768517 ]]
Середнє значення: 0.44836544300911735
Сума елементів, менших за середнє значення: 3.668452992318522


In [ ]:
#Завдання 5
#Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами від 1 до 30 та виконайте на них поелементні операції додавання, віднімання та множення.

array1 = np.random.randint(1, 31, size=5)
array2 = np.random.randint(1, 31, size=5)
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
print("Масив 1:", array1)
print("Масив 2:", array2)
print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)


Масив 1: [24 11 19 15 28]
Масив 2: [ 5 21 21  8  6]
Додавання: [29 32 40 23 34]
Віднімання: [ 19 -10  -2   7  22]
Множення: [120 231 399 120 168]


In [ ]:
#Завдання 6
#Створіть дві матриці 3x3, заповніть їх довільними дійсними числами від 0 до 1 та знайдіть їх добуток.

matrix1 = np.random.random((3, 3))
matrix2 = np.random.random((3, 3))
product = np.dot(matrix1, matrix2)
print("Матриця 1:\n", matrix1)
print("Матриця 2:\n", matrix2)
print("Добуток матриць:\n", product)


Матриця 1:
 [[0.21454163 0.42025348 0.85821268]
 [0.76138141 0.11636611 0.49801342]
 [0.15859781 0.45207568 0.23728879]]
Матриця 2:
 [[0.14308347 0.14376373 0.35094653]
 [0.72131929 0.37773684 0.24999007]
 [0.33027389 0.87968578 0.92009271]]
Добуток матриць:
 [[0.61727954 0.94454602 0.96998707]
 [0.35735905 0.59151013 0.75451305]
 [0.42715393 0.40230583 0.38700147]]


In [ ]:
#Завдання 7
#Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 2))
product = np.dot(matrix1, matrix2)
print("Матриця 1 (2x3):\n", matrix1)
print("Матриця 2 (3x2):\n", matrix2)
print("Добуток матриць:\n", product)


Матриця 1 (2x3):
 [[2 1 1]
 [5 2 4]]
Матриця 2 (3x2):
 [[1 2]
 [1 1]
 [1 5]]
Добуток матриць:
 [[ 4 10]
 [11 32]]


In [ ]:
#Завдання 8
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

matrix = np.random.randint(1, 11, size=(3, 3))
print("Матриця:")
print(matrix)
if np.linalg.det(matrix) == 0:
    print("Матриця є сингулярною і не має оберненої матриці.")
else:

    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)


Матриця:
[[3 1 4]
 [4 3 5]
 [3 6 1]]
Обернена матриця:
[[ 2.7 -2.3  0.7]
 [-1.1  0.9 -0.1]
 [-1.5  1.5 -0.5]]


In [ ]:
#Завдання 9
#Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

matrix = np.random.rand(5, 5)
print("Оригінальна матриця:")
print(matrix)
transposed_matrix = np.transpose(matrix)
print("Транспонована матриця:")
print(transposed_matrix)



Оригінальна матриця:
[[0.6178188  0.1195418  0.61735275 0.90099319 0.75775585]
 [0.33719367 0.22187355 0.97599667 0.37939732 0.29153843]
 [0.23610904 0.02263152 0.71508804 0.73806431 0.03597742]
 [0.77591755 0.58312391 0.73210012 0.74590968 0.05494716]
 [0.45009417 0.38598779 0.83193352 0.13883558 0.27223814]]
Транспонована матриця:
[[0.6178188  0.33719367 0.23610904 0.77591755 0.45009417]
 [0.1195418  0.22187355 0.02263152 0.58312391 0.38598779]
 [0.61735275 0.97599667 0.71508804 0.73210012 0.83193352]
 [0.90099319 0.37939732 0.73806431 0.74590968 0.13883558]
 [0.75775585 0.29153843 0.03597742 0.05494716 0.27223814]]


In [ ]:
#Завдання 10
#Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від -5 до 5, а вектор - випадковими дійсними числами від 0 до 1 і знайдіть добуток матриці на вектор

matrix = np.random.randint(-5, 6, size=(3, 4))
vector = np.random.rand(4, 1)
print("Матриця 3x4:")
print(matrix)
print("Вектор 4x1:")
print(vector)
product = np.dot(matrix, vector)
print("Добуток матриці на вектор:")
print(product)



Матриця 3x4:
[[ 4 -2  3 -4]
 [ 2  3 -4  4]
 [ 3 -4  3 -1]]
Вектор 4x1:
[[0.43607612]
 [0.62817444]
 [0.53124301]
 [0.74573588]]
Добуток матриці на вектор:
[[-0.90125886]
 [ 3.61464701]
 [-0.35647622]]


In [ ]:
#Завдання 11
#Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

matrix = np.random.rand(2, 3)
vector = np.random.rand(3, 1)
print("Матриця 2x3:")
print(matrix)
print("Вектор 3x1:")
print(vector)
product = np.dot(matrix, vector)
print("Добуток матриці на вектор:")
print(product)



Матриця 2x3:
[[0.73384568 0.21769374 0.76723821]
 [0.48280358 0.39645423 0.96263547]]
Вектор 3x1:
[[0.49442866]
 [0.69390864]
 [0.34098551]]
Добуток матриці на вектор:
[[0.77551101]
 [0.84205969]]


In [ ]:
#Завдання 12
#Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму всіх елементів обох матриць

matrix1 = np.random.randint(1, 11, size=(3, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3))
print("Перша матриця 3x3:")
print(matrix1)
print("Друга матриця 3x3:")
print(matrix2)
sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)
total_sum = sum_matrix1 + sum_matrix2
print("Сума всіх елементів першої матриці:", sum_matrix1)
print("Сума всіх елементів другої матриці:", sum_matrix2)
print("Загальна сума всіх елементів обох матриць:", total_sum)


Перша матриця 3x3:
[[6 4 2]
 [4 5 4]
 [1 2 7]]
Друга матриця 3x3:
[[9 5 2]
 [2 8 9]
 [2 2 9]]
Сума всіх елементів першої матриці: 35
Сума всіх елементів другої матриці: 48
Загальна сума всіх елементів обох матриць: 83


In [18]:
#Висновок
#Я навчився використовувати елементи лінійної алгебри використовуючи colab google